services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_DB=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data/countries.csv:/docker-entrypoint-initdb.d/countries.csv
      - ./data/users.csv:/docker-entrypoint-initdb.d/users.csv

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=
      - PGADMIN_DEFAULT_PASSWORD=
    ports:
      - 5050:80
